### ISSUE TITLE
Actividad 2

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-team-lmn#1]
[actividad 2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-team-lmn/files/14300834/actividad.2.pdf)

**Comment by ElisabetRD** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
